[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "resolve-runtime-calculator"
version = "0.1.0"
description = "Runtime calulator for Davinci Resolve"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
authors = [
    { name = "Michael Jordan", email = "michael@glowingpixel.com" }
]
dependencies = [
    "resolve-common @ git+https://github.com/mjiggidy/resolve_common.git",
    "timecode @ git+https://github.com/mjiggidy/timecode.git",
]

[tool.setuptools.packages.find]
where = ["src"]